apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app_environment_id: ebf87eaf-52d5-48f8-bb3b-0e3eb9e022c0
    env_id: ac82d0b0-7250-4388-86ad-7277871c93cb
    env_name: test-env
    organization_id: c569bcc5-3d17-4a08-a77b-693d841360c6
    platformer_app_id: 31bcb57c-87bb-4d00-8bf8-857103982288
    platformer_app_name: tharindu-github
    platformer_component: rudder
    platformer_system: "true"
    project_id: b9bb816b-cf68-43c7-bddc-a92ea9f7743b
  name: tharindu-github
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app_environment_id: ebf87eaf-52d5-48f8-bb3b-0e3eb9e022c0
      env_id: ac82d0b0-7250-4388-86ad-7277871c93cb
      env_name: test-env
      organization_id: c569bcc5-3d17-4a08-a77b-693d841360c6
      platformer_app_id: 31bcb57c-87bb-4d00-8bf8-857103982288
      platformer_app_name: tharindu-github
      platformer_component: rudder
      platformer_system: "true"
      project_id: b9bb816b-cf68-43c7-bddc-a92ea9f7743b
  strategy: {}
  template:
    metadata:
      annotations:
        platformer.com/reload-hash: 148eeebf-d0b2-474d-8c0c-5c73fde70b33
      labels:
        app_environment_id: ebf87eaf-52d5-48f8-bb3b-0e3eb9e022c0
        env_id: ac82d0b0-7250-4388-86ad-7277871c93cb
        env_name: test-env
        organization_id: c569bcc5-3d17-4a08-a77b-693d841360c6
        platformer_app_id: 31bcb57c-87bb-4d00-8bf8-857103982288
        platformer_app_name: tharindu-github
        platformer_component: rudder
        platformer_system: "true"
        project_id: b9bb816b-cf68-43c7-bddc-a92ea9f7743b
    spec:
      imagePullSecrets:
      - name: reg-tharindu-github-3192360657
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
